In [1]:
import torch

##### 1. Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.FloatTensor(3,4,5)
a

tensor([[[9.0244e-37, 0.0000e+00, 9.1084e-44, 2.5111e-42, 9.0226e-37],
         [0.0000e+00, 9.0226e-37, 0.0000e+00, 4.1879e-38, 2.6920e-36],
         [1.4787e-38, 2.6922e-36, 9.0227e-37, 0.0000e+00, 9.0227e-37],
         [0.0000e+00, 1.2124e-38, 5.2911e-38, 1.7179e-34, 4.8501e-38]],

        [[1.2402e-38, 2.7445e-33, 7.9469e-34, 4.3920e-32, 1.2127e-38],
         [7.0273e-31, 1.2127e-38, 1.1244e-29, 1.2128e-38, 1.7990e-28],
         [1.2129e-38, 2.8785e-27, 1.2130e-38, 1.8070e-28, 1.8424e-25],
         [4.8123e-38, 5.2924e-38, 7.3784e-25, 4.8524e-38, 1.1791e-23]],

        [[1.2132e-38, 5.2926e-38, 7.5556e-22, 4.8531e-38, 1.2075e-20],
         [1.2134e-38, 1.9320e-19, 1.2134e-38, 5.2932e-38, 3.0948e-18],
         [4.8540e-38, 4.9460e-17, 1.2136e-38, 7.9138e-16, 1.2136e-38],
         [1.2662e-14, 1.2137e-38, 5.2936e-38, 8.1130e-13, 4.8553e-38]]])

##### 2. Выведите его форму (shape)

In [3]:
a.shape

torch.Size([3, 4, 5])

##### 3. Приведите его к форме 6х10

In [4]:
b = a.view(6,10)
b

tensor([[9.0244e-37, 0.0000e+00, 9.1084e-44, 2.5111e-42, 9.0226e-37, 0.0000e+00,
         9.0226e-37, 0.0000e+00, 4.1879e-38, 2.6920e-36],
        [1.4787e-38, 2.6922e-36, 9.0227e-37, 0.0000e+00, 9.0227e-37, 0.0000e+00,
         1.2124e-38, 5.2911e-38, 1.7179e-34, 4.8501e-38],
        [1.2402e-38, 2.7445e-33, 7.9469e-34, 4.3920e-32, 1.2127e-38, 7.0273e-31,
         1.2127e-38, 1.1244e-29, 1.2128e-38, 1.7990e-28],
        [1.2129e-38, 2.8785e-27, 1.2130e-38, 1.8070e-28, 1.8424e-25, 4.8123e-38,
         5.2924e-38, 7.3784e-25, 4.8524e-38, 1.1791e-23],
        [1.2132e-38, 5.2926e-38, 7.5556e-22, 4.8531e-38, 1.2075e-20, 1.2134e-38,
         1.9320e-19, 1.2134e-38, 5.2932e-38, 3.0948e-18],
        [4.8540e-38, 4.9460e-17, 1.2136e-38, 7.9138e-16, 1.2136e-38, 1.2662e-14,
         1.2137e-38, 5.2936e-38, 8.1130e-13, 4.8553e-38]])

In [5]:
b.shape

torch.Size([6, 10])

##### 4. Создайте случайный IntTensor размера 10

In [6]:
c = torch.IntTensor(10)
c

tensor([ 110839040,          0,         24,          0,         -1,   16843009,
        1668444020, 1767059048, 1529374074,  824192054], dtype=torch.int32)

In [7]:
c.shape

torch.Size([10])

##### 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [8]:
d = b * c
d

tensor([[ 1.0003e-28,  0.0000e+00,  2.1860e-42,  0.0000e+00, -9.0226e-37,
          0.0000e+00,  1.5054e-27,  0.0000e+00,  6.4049e-29,  2.2188e-27],
        [ 1.6390e-30,  0.0000e+00,  2.1654e-35,  0.0000e+00, -9.0227e-37,
          0.0000e+00,  2.0228e-29,  9.3496e-29,  2.6273e-25,  3.9974e-29],
        [ 1.3746e-30,  0.0000e+00,  1.9073e-32,  0.0000e+00, -1.2127e-38,
          1.1836e-23,  2.0234e-29,  1.9869e-20,  1.8549e-29,  1.4828e-19],
        [ 1.3444e-30,  0.0000e+00,  2.9112e-37,  0.0000e+00, -1.8424e-25,
          8.1053e-31,  8.8300e-29,  1.3038e-15,  7.4212e-29,  9.7182e-15],
        [ 1.3447e-30,  0.0000e+00,  1.8133e-20,  0.0000e+00, -1.2075e-20,
          2.0437e-31,  3.2234e-10,  2.1442e-29,  8.0952e-29,  2.5507e-09],
        [ 5.3801e-30,  0.0000e+00,  2.9126e-37,  0.0000e+00, -1.2136e-38,
          2.1327e-07,  2.0250e-29,  9.3542e-29,  1.2408e-03,  4.0017e-29]])

In [9]:
d.shape

torch.Size([6, 10])

##### 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
##### Подсказка: .dot может не подойти

In [10]:
dd = torch.mm(d,torch.t(d))
dd

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 2.1562e-41, 6.1447e-36, 7.9471e-32],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 5.1007e-43, 1.0848e-37, 3.2599e-28],
        [0.0000e+00, 0.0000e+00, 2.2380e-38, 1.4669e-33, 3.7821e-28, 2.5473e-30],
        [2.1562e-41, 5.1007e-43, 1.4669e-33, 9.6144e-29, 2.4789e-23, 9.2081e-32],
        [6.1447e-36, 1.0848e-37, 3.7821e-28, 2.4789e-23, 6.6101e-18, 1.0044e-31],
        [7.9471e-32, 3.2599e-28, 2.5473e-30, 9.2081e-32, 1.0044e-31, 1.5395e-06]])

In [11]:
dd.shape

torch.Size([6, 6])

##### 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [12]:
x=torch.tensor(1.0, requires_grad=True) 
z=torch.tensor(0.5, requires_grad=True) 
t=torch.tensor(2.0, requires_grad=True) 
y=torch.pow(x,3) + z - 75*t 
y.backward() 
print(x.grad) 
print(z.grad) 
print(t.grad) 


tensor(3.)
tensor(1.)
tensor(-75.)


##### 8. Создайте единичный тензор размера 5x6

In [13]:
o = torch.ones(5,6)
o

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

##### 9. Переведите его в формат numpy

In [14]:
o.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)